name: Release

on:
  workflow_dispatch:
    inputs:
      repository:
        default: skeeto/w64devkit
        required: true
      ref:
        default: master
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [x86, amd64]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: src

    - name: Patch
      run: |
        patch -p 0 -u -i minimal.patch
        cp minimal-pe-header.patch src
        if [ ${{ matrix.variant }} = x86 ]; then
          perl -i -p -e '
            s/(ARG ARCH=)x86_64-w64-mingw32/${1}i686-w64-mingw32/;
            s/--disable-lib32/--enable-lib32/;
            s/--enable-lib64/--disable-lib64/;
            print
              "        --with-default-win32-winnt=0x0501 \\\n" .
              "        --with-arch=pentium4 \\\n"
              if /with-default-msvcrt=msvcrt-os/;
            print "        --disable-win32-utf8-manifest \\\n"
              if /disable-win32-registry/;
          ' src/Dockerfile
        fi

    - name: Build
      run: docker buildx b -t mingw src

    - name: Run
      run: docker run --rm mingw > mingw-${{ matrix.variant }}.exe

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: mingw-${{ matrix.variant }}
        path: mingw-${{ matrix.variant }}.exe

  release:
    needs: [build]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4

    - uses: GeekyEggo/delete-artifact@v5
      if: always()
      with: { name: mingw-* }

    - name: Get date
      id: date
      run: printf $'date=%s\n' "$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: mingw-*/*.exe
        tag_name: r${{ steps.date.outputs.date }}
        body: Release ${{ steps.date.outputs.date }}
