name: Release

on:
  workflow_dispatch:
    inputs:
      repository:
        default: skeeto/w64devkit
        required: true
      ref:
        default: master
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [x86, amd64]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: src

    - name: Patch
      run: |
        patch -p 0 -u -i minimal.patch
        if [ ${{ matrix.variant }} = x86 ]; then
          patch -p 0 -u -i minimal-32.patch
        fi
        cp binutils-minimal-pe-header.patch src/src

    - name: Build
      run: docker buildx b -t mingw src

    - name: Run
      run: docker run --rm mingw > mingw-${{ matrix.variant }}.exe

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: mingw-${{ matrix.variant }}
        path: mingw-${{ matrix.variant }}.exe

  release:
    needs: [build]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4

    - uses: GeekyEggo/delete-artifact@v5
      if: always()
      with: { name: mingw-* }

    - name: Get date
      id: date
      run: printf $'date=%s\n' "$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: mingw-*/*.exe
        tag_name: r${{ steps.date.outputs.date }}
        body: Release ${{ steps.date.outputs.date }}
